---
version: '3'

includes:
  security:
    taskfile: ./security/Taskfile.yml
  docker-compose:
    taskfile: ./docker-compose/Taskfile.yml
  terraform:
    taskfile: ./terraform/terraform.yml
  cdktf:
    taskfile: ./terraform/cdktf.yml
  terragrunt:
    taskfile: ./terraform/terragrunt.yml
